steps:
- name: gcr.io/cloud-builders/docker:latest
  args: ['build', '--tag=${_DOCKER_NAMESPACE}/python-compat-multicore:${_TAG}',
         '--no-cache', '.']
images: [
  '${_DOCKER_NAMESPACE}/python-compat-multicore:${_TAG}',
]
